CREATE TABLE IF NOT EXISTS course_learning_outcomes (
    id BIGINT NOT NULL AUTO_INCREMENT,
    course_id BIGINT NOT NULL,
    content VARCHAR(1024) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),

    CONSTRAINT fk_clo_course_id FOREIGN KEY (course_id)
    REFERENCES courses (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
) ENGINE=InnoDB;