spring:
  application:
    name: elearning

  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/motedu_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration


jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}